- name: Create Tomcat group
  group: name=tomcat

- name: Create Tomcat user
  user: name=tomcat group=tomcat shell=/sbin/nologin

- name: Clean temporary
  file: path=/tmp/{{tomcat_archive_directory_name}}* state=absent

- name: Download Tomcat archive file
  get_url: url={{tomcat_download_url}} dest=/tmp/{{tomcat_archive_directory_name}}.tar.gz

- name: Extract Tomcat
  unarchive:
    src: /tmp/{{tomcat_archive_directory_name}}.tar.gz
    dest: /tmp
    owner: tomcat
    group: tomcat

- name: Move to Tomcat home
  command: mv /tmp/{{tomcat_archive_directory_name}} {{tomcat_home}}

- name: Add Tomcat systemd
  template:
    src: tomcat.service.j2
    dest: /usr/lib/systemd/system/{{tomcat_service_name}}.service
    owner: tomcat
    group: tomcat
    mode: 0644

- name: Systemd daemon reload
  shell: systemctl daemon-reload

- name: Start Tomcat
  service: name={{tomcat_service_name}} state=restarted enabled=yes
