- name: Create Tomcat group
  group: name=tomcat

- name: Create Tomcat user
  user: name=tomcat group=tomcat shell=/sbin/nologin

- name: Clean temporary
  file: path=/tmp/{{tomcat_archive_directory_name}}* state=absent

- name: Download Tomcat archive file
  get_url: url={{tomcat_download_url}} dest=/tmp/{{tomcat_archive_directory_name}}.tar.gz

- name: Extract Tomcat
  unarchive: src=/tmp/{{tomcat_archive_directory_name}}.tar.gz dest=/tmp

- name: Move to Tomcat home
  command: mv /tmp/{{tomcat_archive_directory_name}} {{tomcat_home}}
