- name: Install Java
  yum: name=java-{{java_version}}

- name: Create Tomcat group
  group: name=tomcat

- name: Create Tomcat user
  user: name=tomcat group=tomcat shell=/sbin/nologin

- name: Check exists Tomcat
  stat: path={{tomcat_install_directory}}/apache-tomcat-{{tomcat_version}}
  register: tm

- name: Download Tomcat archive file
  get_url: url={{tomcat_download_url}} dest=/tmp/apache-tomcat-{{tomcat_version}}.tar.gz
  when: not tm.stat.exists

- name: Extract Tomcat
  unarchive:
    src: /tmp/apache-tomcat-{{tomcat_version}}.tar.gz
    dest: '{{tomcat_install_directory}}'
    owner: tomcat
    group: tomcat
  when: not tm.stat.exists

- name: Set Tomcat home directory symlink
  file: src={{tomcat_install_directory}}/apache-tomcat-{{tomcat_version}} path={{tomcat_home}} state=link force=yes

- name: Add Tomcat systemd
  template:
    src: tomcat.service.j2
    dest: /usr/lib/systemd/system/{{tomcat_service_name}}.service
    owner: tomcat
    group: tomcat
    mode: 0644

- name: Systemd daemon reload
  shell: systemctl daemon-reload

- name: Start Tomcat
  service: name={{tomcat_service_name}} state=restarted enabled=yes
